@php($editingMagazine=$magazine ?? null)
<section class="admin-form-card"><div class="admin-field-grid">
<label class="admin-span-2">Title<input name="title" value="{{ old('title',$editingMagazine?->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug',$editingMagazine?->slug) }}"></label><label>Issue date<input type="date" name="issue_date" value="{{ old('issue_date',$editingMagazine?->issue_date?->format('Y-m-d')) }}"></label>
<label>Cover image path<input name="cover_image" value="{{ old('cover_image',$editingMagazine?->cover_image) }}"></label><label>Cover alt text<input name="cover_image_alt" value="{{ old('cover_image_alt',$editingMagazine?->cover_image_alt) }}"></label>
<label class="admin-span-2">Private PDF path <small>Store paid PDFs under <code>storage/app/private</code>.</small><input name="pdf_path" value="{{ old('pdf_path',$editingMagazine?->pdf_path) }}" required></label>
<label>Price<input type="number" step="0.01" min="0" name="price" value="{{ old('price',$editingMagazine?->price ?? 0) }}" required></label><label class="admin-check-field"><input type="hidden" name="is_free" value="0"><input type="checkbox" name="is_free" value="1" @checked(old('is_free',$editingMagazine?->is_free))> Free issue</label>
<label class="admin-check-field"><input type="hidden" name="allow_download" value="0"><input type="checkbox" name="allow_download" value="1" @checked(old('allow_download',$editingMagazine?->allow_download ?? true))> Allow download</label><label class="admin-check-field"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$editingMagazine?->is_active ?? true))> Active</label>
<label class="admin-span-2">Description<textarea name="description" rows="8">{{ old('description',$editingMagazine?->description) }}</textarea></label>
</div></section>
<section class="admin-form-card"><div class="admin-field-grid"><label>Meta title<input name="meta_title" value="{{ old('meta_title',$editingMagazine?->meta_title) }}"></label><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url',$editingMagazine?->canonical_url) }}"></label><label class="admin-span-2">Meta description<textarea name="meta_description" rows="4">{{ old('meta_description',$editingMagazine?->meta_description) }}</textarea></label></div></section>
